version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: mastermind
      POSTGRES_USER: mastermind
      POSTGRES_PASSWORD: mastermind
    ports:
      - 5432:5432

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
      - "15674:15674"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      - "traefik.ws.port=15674"
      - "traefik.ws.frontend.rule=PathPrefixStrip:/stomp/"
      - "traefik.web.port=15672"
      - "traefik.web.frontend.rule=PathPrefixStrip:/rabbit/"

  server:
    image: sotomski/mastermind-server
    build: .
    ports:
      - 8000:8000
    environment:
      AMQP_URL: amqp://guest:guest@rabbit:5672/
      DB_HOST: postgres
    volumes:
      - ./storage:/root/storage
    labels:
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  worker:
    image: sotomski/mastermind-worker
    build: ../mastermind-worker
    environment:
      AMQP_URL: amqp://guest:guest@rabbit:5672/
      DB_HOST: postgres
    volumes:
      - ./storage:/root/storage

  web:
    image: sotomski/mastermind
    build: ../mastermind
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/"

  traefik:
    image: traefik:1.7
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--defaultentrypoints=http"
      - "--docker"
      - "--docker.domain=lvh.me"
      - "--docker.watch"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
