version: "3"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: deploji
      POSTGRES_USER: deploji
      POSTGRES_PASSWORD: deploji
    ports:
      - 5432:5432

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      - "traefik.web.port=8081"
      - "traefik.web.frontend.rule=PathPrefixStrip:/mongo/"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
      - "15674:15674"
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=default"
      - "traefik.ws.port=15674"
      - "traefik.ws.frontend.rule=PathPrefixStrip:/stomp/"
      - "traefik.web.port=15672"
      - "traefik.web.frontend.rule=PathPrefixStrip:/rabbit/"

  server:
    image: deploji/deploji-server
    build: .
    ports:
      - 8000:8000
    environment:
      AMQP_URL: amqp://guest:guest@rabbit:5672/
      DB_HOST: postgres
    volumes:
      - ./storage:/root/storage
    labels:
      - "traefik.enable=true"
      - "traefik.port=8000"
      - "traefik.frontend.rule=PathPrefixStrip:/api/"

  scheduler:
    image: deploji/deploji-scheduler
    build: ../deploji-scheduler
    ports:
      - 8001:8001
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=example
      - SPRING_DATA_MONGODB_DATABASE=deploji-scheduler
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - DEPLOJI_API_URL=http://localhost:8000
      - DEPLOJI_JWT_SECRET=38ur43qrh43qti8314t3842qt93814tr93284y
      - DEPLOJI_JWT_EXPIRATION=6000
    labels:
      - "traefik.enable=true"
      - "traefik.port=8001"
      - "traefik.frontend.rule=PathPrefixStrip:/api/schedules"

  worker:
    image: deploji/deploji-worker
    build: ../deploji-worker
    environment:
      AMQP_URL: amqp://guest:guest@rabbit:5672/
      DB_HOST: postgres
    volumes:
      - ./storage:/root/storage

  web:
    image: deploji/deploji
    build: ../deploji
    volumes:
    - ../deploji:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefixStrip:/"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    labels:
      - "traefik.enable=true"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailhog.localhost"

  traefik:
    image: traefik:1.7
    command:
      - "--api"
      - "--entrypoints=Name:http Address::80"
      - "--defaultentrypoints=http"
      - "--docker"
      - "--docker.domain=lvh.me"
      - "--docker.watch"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
